version: "3"
services:

  freeciv-web:
    image: freeciv/freeciv-web:1.3.1
    build: .
    container_name: freeciv-web
    command: ["sleep", "infinity"]
    ports:
      - "8080:80"
      - "4002:4002"
      - "6000-6009:6000-6009"
      - "7000-7009:7000-7009"
      - "8888:8080"
    user: docker

